version: "3"
services:
  mcp-minimax:
    platform: linux/amd64
    container_name: "mcp-minimax"
    build: ./
    image: "ghcr.io/acedatacloud/mcp-minimax:${BUILD_NUMBER}"
    ports:
      - "8000:8000"
